# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return


export HISTSIZE=10000000
export HISTFILESIZE=1000000000
# do'nt put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups,erasedups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    export CLICOLOR=1
#    eval "`dircolors -b`"
    #alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

#shopt -s direxpand

if [ -d ~/.bashrc.d ]; then
  for i in ~/.bashrc.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export MALLOC_MMAP_THRESHOLD_=524288

# some nvim features
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1


# python stdin/stdout/stderr encoding
export PYTHONIOENCODING=utf-8

# rust racer
export RUST_SRC_PATH=/home/code/rust/rust/src

# try to fix pynvim problem
stty erase '^?'

# powerline prompt
#. ~/.bash_prompt

# https://github.com/neovim/neovim/issues/1415
prefixes_dir="$HOME/.opt"

if [[ -d $prefixes_dir ]]; then
    for dir in "$prefixes_dir"/*; do
        dir=${dir:A}
        if [[ -d "$dir/bin" ]]; then
            PATH="$dir/bin:$PATH"
        fi
        if [[ -d "$dir/share/man" ]]; then
            MANPATH="$dir/share/man:$MANPATH"
        fi
        if [[ -d "$dir/lib" ]]; then
            LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$dir/lib"
        fi
        if [[ -d "$dir/lib/pkgconfig" ]]; then
            PKG_CONFIG_PATH="$dir/lib/pkgconfig:$PKG_CONFIG_PATH"
        fi
    done
fi
unset dir prefixes_dir
export PATH MANPATH LD_LIBRARY_PATH PKG_CONFIG_PATH


# https://github.com/junegunn/fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
